---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: true
      changed_when: false
      when: ansible_os_family == 'Debian'
    - name: import yaml to disable gettys.
      import_tasks: disable_getty.yml
  vars:
    # cassandra 3.11 doesn't support java 9 yet, use openjdk-8.
    java_packages:
      - openjdk-8-jdk
  roles:
    - ansible-role-ntp
    - ansible-role-java
    - ansible-cassandra
  post_tasks:
    - name: show seed nodes
      debug: var=cassandra_seed_resolved
