---
- name: sleep for 120 seconds and continue with play
  wait_for: timeout=120

- name: GetClusterStatusOutput
  shell: "{{ cassandra_path }}/nodetool status"
  changed_when: true
  register: cluster_status

- name: DisplayClusterStatusOutput
  debug: msg="{{ cluster_status.stdout_lines }}"
  run_once: true
