---
- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Increase the vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_map_count }}"
    state: present
